#数据源
spring:
  datasource:
    url: jdbc:mysql:///istudent
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    username: root
dubbo:
  application:
    name: studentService
  registry:
    address: zookeeper://192.168.174.128:2181
  protocol:
    port: 20881